# Generated by Django 2.0.3 on 2018-04-08 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prestador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, verbose_name='Nome')),
                ('endereco', models.CharField(blank=True, default='', max_length=100, verbose_name='Endereco')),
                ('telefone', models.CharField(blank=True, default='', max_length=20, verbose_name='Telefone')),
                ('observacao', models.TextField(blank=True, default='', verbose_name='Obsrvacoes')),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, default='', verbose_name='Descricao')),
            ],
        ),
        migrations.AddField(
            model_name='prestador',
            name='tipo',
            field=models.ForeignKey(on_delete='models.CASCADE', to='servicos.Servico', verbose_name='Tipo Servico'),
        ),
    ]
